### ISSUE TITLE
如何添加一张新的图片进行推理呢

### ISSUE THREAD

**Issue by sihuo521** [airxiechao/simple-car-plate-recognition#4]
看了工程代码里带的推理代码，是从val文件夹选的一张图片。

**Comment by airxiechao** [comment]
图片样本就是个numpy的array

**Comment by sihuo521** [comment]
> 图片样本就是个numpy的array
首先感谢您的回复。我换了自己的图片后，运行到这一行：x0 = np.min([i%image.shape[0] for i in p])
会报错：ValueError: zero-size array to reduction operation minimum which has no identity
而且p = np.where(r['masks'].flatten() == True)[0]中的p是空的。这是什么原因呢？
