### ISSUE TITLE
字符识别训练测试数据一致吗？

### ISSUE THREAD

**Issue by YFZh** [airxiechao/simple-car-plate-recognition#5]
Hi！感谢开源工作。我看你上传的单字符识别的训练集是二值图，但是测试时用的灰度图，是这样吗？如果如此，识别准确率不会受影响吗？

**Comment by Mrdsj** [comment]
I had run this code,it can segment different characters,but can't recognize them all sometimes,though the characters are clear enough.

**Comment by airxiechao** [comment]
> I had run this code,it can segment different characters,but can't recognize them all sometimes,though the characters are clear enough.

字符分割如果能去除上下左右的空白，结果会准一点，但是分割是基于一些手工图形处理方法，结果很不稳定
